export default {
    SUCCESS: `The Operation has been Sucessful`,
    SOMETHING_WENT_WRONG: `Something went wrong`,
    NOT_FOUND: (entity: string)=> `${entity} not found`,
    TOO_MANY_REQUESTS : `Too Many Requests. Try again after sometime`,
    INVALID_PHONE_NUMBER : `Invaild Phone Number`,
    ALREADY_EXIST: (entity: string, identifier: string) => `${entity} is already exist with ${identifier}`,
    CREATED_SUCCESSFULLY: (entity: string) => `${entity} created successfully`,
    UPDATED_SUCCESSFULLY: (entity: string) => `${entity} updated successfully`,
    INVALID_CONFIRMATION_TOKEN_OR_CODE : `Invalid Confirmation Token or Code`,
    ACCOUNT_ALREADY_CONFIRMED: `Account already confirmed`,
    INVALID_EMAIL_OR_PASSWORD: `Invalid Email or Password`,
    UNAUTHORISED: `You are UnAuthorised to Perform this action`,
    ACCOUNT_CONFIRMATION_REQUIRED: `Account Confirmation Required`,
    URL_EXPIRED: `Password Reset url is Expired`,
    INVALID_REQUEST: `Invalid Request`,
    INVALID_OLD_PASSWORD: `Invalid old Password`,
    NEW_PASSWORD_MATCHING_OLD_PASSWORD: `New Password is matching with Old Password`,
    INVALID: (entity: string) => `Invalid ${entity}`,
    SAME_REQUEST_ROLE: (entity: string) => `You are already an ${entity}`,
    ACTION_CANT_BE_DONE: `The Requested action can't be done`
}